# Generated by Django 4.0.5 on 2022-08-31 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExamCohort', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Right_Answer', models.CharField(max_length=100)),
                ('Given_Answer', models.CharField(max_length=100)),
                ('Attempted', models.CharField(max_length=50)),
                ('Mark', models.IntegerField(max_length=50)),
                ('Assessment_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamCohort.assessments')),
                ('Candidate_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamCohort.questions')),
            ],
        ),
    ]
