# Generated by Django 4.0.5 on 2022-09-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assessments', '0002_alter_marksheet_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='Viva_answer',
            field=models.FileField(blank=True, null=True, upload_to='records'),
        ),
    ]
