# Generated by Django 4.0.5 on 2022-08-05 17:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('startDate', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamCohort',
            fields=[
                ('EvaluatorId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamCohort.assessments')),
            ],
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('questions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExamCohort.questions')),
                ('Question_Text', models.CharField(max_length=255)),
                ('Choice_1', models.CharField(max_length=50)),
                ('Choice_2', models.CharField(max_length=50)),
                ('Choice_3', models.CharField(max_length=50)),
                ('Choice_4', models.CharField(max_length=50)),
                ('Answer', models.CharField(max_length=50)),
                ('Time_limit_in_seconds', models.IntegerField(default=120, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(120)])),
            ],
            bases=('ExamCohort.questions',),
        ),
        migrations.CreateModel(
            name='MicroViva',
            fields=[
                ('questions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ExamCohort.questions')),
                ('Question_name', models.CharField(blank=True, max_length=200, null=True)),
                ('voice_record', models.FileField(blank=True, null=True, upload_to='records')),
                ('Answer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('answer_record', models.FileField(blank=True, null=True, upload_to='records')),
            ],
            bases=('ExamCohort.questions',),
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('EvaluatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamCohort.examcohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assessments',
            name='EvaluatorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExamCohort.examcohort'),
        ),
    ]
