# Generated by Django 4.0.5 on 2022-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamCohort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='Mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
