# Generated by Django 4.0.5 on 2022-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamCohort', '0002_mcq_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='microviva',
            name='Answer_text',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
